### ISSUE TITLE
use_gpu = True / RuntimeError at T3D policy

### ISSUE THREAD

**Issue by Mickey-dmeta** [aiAdrian/flatland_solver_policy#2]
thanks for the update :)

case : 
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

The problem is some variable is on cpu only

we edited it as below

self.total_it += 1

# Sample replay buffer
states, actions, rewards, states_next, dones, _ = self.memory.sample()
actions = F.one_hot(torch.squeeze(actions), num_classes=self.action_size).to(self.device)
states_next = torch.squeeze(states_next).to(self.device)
rewards = torch.squeeze(rewards).to(self.device)
dones = torch.squeeze(dones).to(self.device)

with torch.no_grad():
    # Select action according to policy and add clipped noise
    noise = (torch.randn(states_next.shape[0], states_next.shape[1]) * self.policy_noise).clamp(
        -self.noise_clip,
        self.noise_clip).to(self.device)
    noisy_actions = self.actor_target(states_next + noise)
    noisy_action_greedy = torch.argmax(noisy_actions, dim=1)
    next_actions = F.one_hot(noisy_action_greedy, num_classes=self.action_size)

**Comment by aiAdrian** [comment]
dear @Mickey-dmeta please check out the fix (https://github.com/aiAdrian/flatland_solver_policy/pull/3) if everything is working well, you could try to merge or give feedback that it's ok or not.

**Comment by Mickey-dmeta** [comment]
everything is well
thx

**Comment by aiAdrian** [comment]
Thank you for reporting the error and helping to solve it.
